#!/bin/bash
if [ "$(id -u)" != "0" ]; then
	echo "You must run this script as root"
	exit 0
fi

if [ "$1" = "-h" ] ||
	[ "$1" = "--help" ] ||
	 [ "$#" = "0" ]; then
		echo "Just type: derepairperm username, to repair permission"
		echo "	by executing command: chown -R username.username /home/username"
		exit 0
fi

if [ ! -e /home/$1 ]; then
	echo "User home folder not found (searching in /home/$1)"
	exit 0
fi

chown -R $1.$1 /home/$1
